
CLDOC=NNtoPred aboutlogic aboutnewterm aboutrefs aboutunifsubst commbasedrule generalthought howtowrite commhowto whatissame aboutJapanesePred todo20190218 substapplyunify provingandrefutation
CLTEX=${CLDOC:=.tex}
CLPDF=${CLDOC:=.pdf}

CLPDFDIR = ../../pdf/cheaplogic

#all: 
#	@echo doc: ${CLDOC} 
#	@echo tex: ${CLTEX} 
#	@echo pdf: ${CLPDF} 
#	@echo ${CLPDFDIR}

public:
	cp ${CLPDF} ${CLPDFDIR}

clean:
	rm *.aux *.log *.gz *.toc

